FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000
EXPOSE 9229

CMD ["sh", "-c", "npx prisma generate && npx prisma db push && npx tsx prisma/seed.ts && npm run start:debug"]
